name: "BugBot Context"
description: "Fetch PR diff, package changed files into a ZIP, and upload both as artifacts."
inputs:
  github-token:
    description: "GitHub token for GraphQL and API calls"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Determine merge-base SHA
      id: find_merge_base
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          // call the REST /compare endpoint
          const resp = await github.rest.repos.compareCommits({
            owner: context.repo.owner,
            repo:  context.repo.repo,
            base:  context.payload.pull_request.base.sha,
            head:  context.payload.pull_request.head.sha
          });
          return resp.data.merge_base_commit.sha;
        result-encoding: string

    - name: Fetch merge-base commit
      shell: bash
      run: |
        git fetch --no-tags --depth=1 origin ${{ steps.find_merge_base.outputs.result }}

    - name: Generate diff
      id: get_diff
      shell: bash
      run: |
        git diff ${{ steps.find_merge_base.outputs.result }} HEAD -U50 > pr_diff.txt

    - name: Upload diff artifact
      uses: actions/upload-artifact@v4
      with:
        name: pr-diff
        path: pr_diff.txt

    - name: Prepare ZIP of changed files
      id: prepare_zip
      shell: bash
      run: |
        zip_file="changed_files_archive.zip"
        staging=$(mktemp -d)
        git diff --name-only -z ${{ steps.find_merge_base.outputs.result }} HEAD \
          | while IFS= read -r -d '' f; do
              if [ -f "$f" ]; then
                mkdir -p "$staging/$(dirname "$f")"
                cp "$f" "$staging/$f"
              fi
            done
        (cd "$staging" && zip -qr "$GITHUB_WORKSPACE/$zip_file" .)
        echo "zip-path=$GITHUB_WORKSPACE/$zip_file" >> "$GITHUB_OUTPUT"

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: changed-files-archive
        path: ${{ steps.prepare_zip.outputs.zip-path }}
